#version 450

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) buffer Self { float self_data[]; };
layout(set = 0, binding = 1) readonly buffer T1 { float t1[]; };
layout(set = 0, binding = 2) readonly buffer T2 { float t2[]; };

layout(push_constant) uniform PC {
    uint numel;
    float value;
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= numel) return;

    self_data[idx] = self_data[idx] + value * t1[idx] / t2[idx];
}
